# Generated by Django 5.2.15 on 2026-07-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='File',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='FileName',
            field=models.CharField(max_length=100),
        ),
    ]
